sonar.projectKey=pleaseai_emulate
sonar.organization=pleaseai

sonar.sources=packages
sonar.exclusions=**/dist/**,**/node_modules/**,**/__tests__/**
sonar.tests=packages
sonar.test.inclusions=**/__tests__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
